---
- name: Ensure Skynet's dependencies are installed.
  apt:
    name: "{{ item }}"
    state: installed
  when: ansible_os_family == 'Debian'
  with_items:
    - python-pip
    - python-dev
    - build-essential
    - python-mysqldb
    - supervisor

- name: Install Cement
  pip:
    name: cement
    state: present

- name: Allow 'aegir' user to restart Skynet queue
  copy:
    dest: "/etc/sudoers.d/{{ aegir_user }}-skynet"
    content: |
     {{ aegir_user }} ALL=NOPASSWD: /usr/bin/supervisorctl start skynet-queue
     {{ aegir_user }} ALL=NOPASSWD: /usr/bin/supervisorctl stop skynet-queue
     {{ aegir_user }} ALL=NOPASSWD: /usr/bin/supervisorctl restart skynet-queue\n
    mode: 0440

- name: Clone Skynet
  git:
    repo: "{{ valkyrie_skynet_repo }}"
    dest: "{{ aegir_root }}/.drush/skynet"
    depth: 1 # speeds things up
    version: "{{ valkyrie_skynet_version }}"
    update: "{{ valkyrie_skynet_update }}"
  sudo: yes
  sudo_user: "{{ aegir_user }}"
  notify:
    - Clear Drush cache
    - Verify Aegir front-end

- name: Create Skynet config file
  meta: flush_handlers

- name: Add Skynet Supervisor config
  template:
    src: skynet-queue.conf.j2
    dest: /etc/supervisor/conf.d/skynet-queue.conf
  notify: Reload Supervisor

- name: Start Skynet via Supervisor
  supervisorctl:
    name: skynet-queue
    state: started
